#!/bin/bash

# ref: https://github.com/bitnami/containers/blob/main/bitnami/postgresql/14/debian-11/rootfs/opt/bitnami/scripts/postgresql/setup.sh
. /opt/bitnami/scripts/libpostgresql.sh

if [ ! -z "${VEGA_POSTGRES_USER}" ]; then
   echo "CREATE USER ${VEGA_POSTGRES_USER} WITH SUPERUSER PASSWORD '${VEGA_POSTGRES_PASSWORD}'" \
      | postgresql_execute "$POSTGRESQL_DATABASE" "$POSTGRESQL_INITSCRIPTS_USERNAME" "$POSTGRESQL_INITSCRIPTS_PASSWORD"

fi;


echo "CREATE DATABASE ${VEGA_POSTGRES_USER}; GRANT ALL PRIVILEGES ON DATABASE ${VEGA_POSTGRES_USER} TO ${VEGA_POSTGRES_USER}" \
   | postgresql_execute "$POSTGRESQL_DATABASE" "$POSTGRESQL_INITSCRIPTS_USERNAME" "$POSTGRESQL_INITSCRIPTS_PASSWORD"

IFS=","
for v in $POSTGRES_DBS; do
   echo "CREATE DATABASE $v with OWNER='${VEGA_POSTGRES_USER}'; GRANT ALL PRIVILEGES ON DATABASE $v TO ${VEGA_POSTGRES_USER}" \
      | postgresql_execute "$POSTGRESQL_DATABASE" "$POSTGRESQL_INITSCRIPTS_USERNAME" "$POSTGRESQL_INITSCRIPTS_PASSWORD"
done