name: Docker / console-test

on:
  push:
    branches:
      - main
    paths:
      - 'console-test/version.json'
  pull_request:
    paths:
      - 'console-test/**'
      - '.github/workflows/docker-console-test.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker/.github/workflows/docker-generic.yml@main
    with:
      image_name: console-test
      docker_context_path: ./console-test
      platforms: linux/amd64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
