name: Docker / smartcontracts-base

on:
  push:
    branches:
      - main
    paths:
      - 'smartcontracts-base/version.json'
  pull_request:
    paths:
      - 'smartcontracts-base/**'
      - '.github/workflows/docker-smartcontracts-base.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker/.github/workflows/docker-generic.yml@main
    with:
      image_name: smartcontracts-base
      docker_context_path: ./smartcontracts-base
      platforms: linux/amd64,linux/arm64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}