name: Docker / github-runner

on:
  push:
    branches:
      - main
    paths:
      - 'github-runner/version.json'
  pull_request:
    paths:
      - 'github-runner/**'
      - '.github/workflows/docker-github-runner.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker-public/.github/workflows/docker-generic.yml@main
    with:
      image_name: github-runner
      docker_context_path: ./github-runner
      platforms: linux/amd64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
