name: Docker / grpc-plugins

on:
  push:
    branches:
      - main
    paths:
      - 'grpc-plugins/version.json'
  pull_request:
    paths:
      - 'grpc-plugins/**'
      - '.github/workflows/docker-grpc-plugins.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker/.github/workflows/docker-generic.yml@main
    with:
      image_name: grpc-plugins
      docker_context_path: ./grpc-plugins
      platforms: linux/amd64, linux/arm64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}