name: Docker / ganache

on:
  push:
    branches:
      - main
    paths:
      - 'ganache/version.json'
  pull_request:
    paths:
      - 'ganache/**'
      - '.github/workflows/docker-ganache.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker-public/.github/workflows/docker-generic.yml@bump-ganache-image
    with:
      image_name: ganache
      docker_context_path: ./ganache
      platforms: linux/amd64, linux/arm64
      upload_artifact: true
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  
  run_tests:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker_image
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install test deps
        working-directory: ./ganache/scripts/testing
        run:
          npm install
      - name: Run token tests
        working-directory: ./ganache/scripts/testing
        run: |
          docker run -rm -p 8545:8545 vegaprotocol/ganache:latest \
            --blockTime 1 \
            --chainId 1440 \
            --networkId 1441 \
            --db /app/ganache-db \
            -h 0.0.0.0 \
            -p 8545 \
            -m "ozone access unlock valid olympic save include omit supply green clown session";
          node test_tokens.js