# Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Reusable workflow to build docker image and publish it

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      docker_context_path:
        required: true
        type: string
      platforms:
        required: true
        type: string

    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

jobs:
  build:
    name: Build the ${{ inputs.image_name }} image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      id: quemu
      uses: docker/setup-qemu-action@v2

    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Collect images data
      id: tags
      run: |
        current=$(jq -r '(.name)+":"+(.version)' "${{ inputs.docker_context_path }}/version.json")
        latest=$(jq -r '(.name)+":latest"' "${{ inputs.docker_context_path }}/version.json")
        echo ::set-output name=current::${current}
        echo ::set-output name=latest::${latest}

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_token }}

    - name: Docker build
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.docker_context_path }}
        file: "${{ inputs.docker_context_path }}/Dockerfile"
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.tags.outputs.latest }},${{ steps.tags.outputs.current }}
        push: ${{ github.event_name != 'pull_request' }}