name: Docker / ganache

on:
  push:
    branches:
      - main
    paths:
      - 'ganache/version.json'
  pull_request:
    paths:
      - 'ganache/**'
      - '.github/workflows/docker-ganache.yml'

jobs:
  build_docker_image:
    uses: vegaprotocol/docker-public/.github/workflows/docker-generic.yml@main
    with:
      image_name: ganache
      docker_context_path: ./ganache
      platforms: linux/amd64, linux/arm64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}